# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, 16
target 'RNMobilePaymentSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNMobilePaymentSDK
  pod "SquareMobilePaymentsSDK", "~> 2.2.3"
  target 'RNMobilePaymentSDKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RNMobilePaymentSDKUITests' do
    # Pods for testing
  end

end
