export enum AccountType {
  SAVINGS = 'SAVINGS',
  CHECKING = 'CHECKING',
  CREDIT = 'CREDIT',
}

export enum AdditionalPaymentMethodType {
  ALL = 'ALL',
  KEYED = 'KEYED',
}

export enum AuthorizationState {
  AUTHORIZED = 'AUTHORIZED',
  AUTHORIZING = 'AUTHORIZING',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
}

export enum CardBrand {
  ALIPAY = 'ALIPAY',
  AMERICAN_EXPRESS = 'AMERICAN_EXPRESS',
  CASH_APP = 'CASH_APP',
  CHINA_UNION_PAY = 'CHINA_UNION_PAY',
  DISCOVER = 'DISCOVER',
  DISCOVER_DINERS = 'DISCOVER_DINERS',
  EBT = 'EBT',
  EFTPOS = 'EFTPOS',
  FELICA = 'FELICA',
  ID = 'ID',
  INTERAC = 'INTERAC',
  JCB = 'JCB',
  MASTERCARD = 'MASTERCARD',
  OTHER_BRAND = 'OTHER_BRAND',
  SQUARE_CAPITAL_CARD = 'SQUARE_CAPITAL_CARD',
  SQUARE_GIFT_CARD = 'SQUARE_GIFT_CARD',
  SUICA = 'SUICA',
  UNKNOWN = 'UNKNOWN',
  VISA = 'VISA',
}

export enum CardCoBrand {
  AFTERPAY = 'AFTERPAY',
  CLEARPAY = 'CLEARPAY',
  NONE = 'NONE',
  UNKNOWN = 'UNKNOWN',
}

export enum CardPaymentStatus {
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  VOIDED = 'VOIDED',
  FAILED = 'FAILED',
  UNKNOWN = 'UNKNOWN',
}

export enum CardInsertionStatus {
  INSERTED = 'INSERTED',
  NOT_INSERTED = 'NOT_INSERTED',
  UNKNOWN = 'UNKNOWN',
}

export enum CurrencyCode {
  AUD = 'AUD',
  CAD = 'CAD',
  EUR = 'EUR',
  GBP = 'GBP',
  JPY = 'JPY',
  USD = 'USD',
}

export enum DelayAction {
  CANCEL = 0,
  COMPLETE = 1,
}

export enum EntryMethod {
  KEYED = 'KEYED',
  SWIPED = 'SWIPED',
  EMV = 'EMV',
  CONTACTLESS = 'CONTACTLESS',
  ON_FILE = 'ON_FILE',
  UNKNOWN = 'UNKNOWN',
}

export enum Environment {
  PRODUCTION = 'PRODUCTION',
  SANDBOX = 'SANDBOX',
}

export enum PaymentStatus {
  APPROVED = 'APPROVED',
  COMPLETE = 'COMPLETE',
  CANCELED = 'CANCELED',
  FAILED = 'FAILED',
  UNKNOWN = 'UNKNOWN',
}

export enum PromptMode {
  DEFAULT = 0,
}

export enum SourceType {
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  CARD = 'CARD',
  CASH = 'CASH',
  EXTERNAL = 'EXTERNAL',
  SQUARE_ACCOUNT = 'SQUARE_ACCOUNT',
  UNKNOWN = 'UNKNOWN',
  WALLET = 'WALLET',
}

// Reader Enums
export enum ReaderBatteryLevel {
  CRITICALLY_LOW = 'CRITICALLY_LOW',
  FULL = 'FULL',
  HIGH = 'HIGH',
  LOW = 'LOW',
  MID = 'MID',
}

export enum ReaderChange {
  BATTERY_DID_BEGIN_CHARGING = 'BATTERY_DID_BEGIN_CHARGING',
  BATTERY_DID_END_CHARGING = 'BATTERY_DID_END_CHARGING',
  BATTERY_LEVEL_DID_CHANGE = 'BATTERY_LEVEL_DID_CHANGE',
  CARD_INSERTED = 'CARD_INSERTED',
  CARD_REMOVED = 'CARD_REMOVED',
  CONNECTION_DID_FAIL = 'CONNECTION_DID_FAIL',
  CONNECTION_STATE_DID_CHANGE = 'CONNECTION_STATE_DID_CHANGE',
  FIRMWARE_UPDATE_DID_FAIL = 'FIRMWARE_UPDATE_DID_FAIL',
  FIRMWARE_UPDATE_PERCENT_DID_CHANGE = 'FIRMWARE_UPDATE_PERCENT_DID_CHANGE',
  STATE_DID_CHANGE = 'STATE_DID_CHANGE',
  //--android
  ADDED = 'ADDED',
  CHANGED_STATE = 'CHANGED_STATE',
  BATTERY_THRESHOLD = 'BATTERY_THRESHOLD',
  BATTERY_CHARGING = 'BATTERY_CHARGING',
  FIRMWARE_PROGRESS = 'FIRMWARE_PROGRESS',
  REMOVED = 'REMOVED',
}

export enum ReaderConnectionFailureRecoverySuggestion {
  ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT',
  CONTACT_SUPPORT = 'CONTACT_SUPPORT',
  NO_SUGGESTION = 'NO_SUGGESTION',
  RETRY = 'RETRY',
  REVIEW_TAP_TO_PAY_GUIDELINES = 'REVIEW_TAP_TO_PAY_GUIDELINES',
  ENABLE_PASSCODE_TO_USE_TAP_TO_PAY = 'ENABLE_PASSCODE_TO_USE_TAP_TO_PAY',
}

export enum ReaderConnectionState {
  CONNECTED = 'CONNECTED',
  CONNECTING = 'CONNECTING',
  FAILED_TO_CONNECT = 'FAILED_TO_CONNECT',
  NOT_CONNECTED = 'NOT_CONNECTED',
}

export enum ReaderFirmwareUpdateError {
  CONNECTION_TIMEOUT = 'CONNECTION_TIMEOUT',
  FIRMWARE_FAILURE = 'FIRMWARE_FAILURE',
  SERVER_CALL_FAILURE = 'SERVER_CALL_FAILURE',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export enum ReaderModel {
  CONTACTLESS_AND_CHIP = 'CONTACTLESS_AND_CHIP',
  EMBEDDED = 'EMBEDDED',
  MAGSTRIPE = 'MAGSTRIPE',
  STAND = 'STAND',
  TAP_TO_PAY = 'TAP_TO_PAY',
  UNKNOWN = 'UNKNOWN',
}

export enum ReaderConnectionFailureReason {
  DENIED_BY_SERVER = 'DENIED_BY_SERVER',
  GENERIC_ERROR = 'GENERIC_ERROR',
  MAX_READERS_CONNECTED = 'MAX_READERS_CONNECTED',
  NETWORK_TIMEOUT = 'NETWORK_TIMEOUT',
  NETWORK_TRANSPORT_ERROR = 'NETWORK_TRANSPORT_ERROR',
  NOT_CONNECTED_TO_INTERNET = 'NOT_CONNECTED_TO_INTERNET',
  READER_TIMEOUT = 'READER_TIMEOUT',
  REVOKED_BY_DEVICE = 'REVOKED_BY_DEVICE',
  SERVER_ERROR = 'SERVER_ERROR',
  TAP_TO_PAY_ERROR = 'TAP_TO_PAY_ERROR',
  UNKNOWN = 'UNKNOWN',
}

export enum ReaderInternalStatus {
  CONNECTING_TO_DEVICE = 'CONNECTING_TO_DEVICE',
  CONNECTING_TO_SQUARE = 'CONNECTING_TO_SQUARE',
  READER_UNAVAILABLE = 'READER_UNAVAILABLE',
  FAULTY = 'FAULTY',
  READY = 'READY',
}

export enum ReaderStatus {
  READY = 'READY',
  CONNECTING_TO_DEVICE = 'CONNECTING_TO_DEVICE',
  CONNECTING_TO_SQUARE = 'CONNECTING_TO_SQUARE',
  FAULTY = 'FAULTY',
  READER_UNAVAILABLE = 'READER_UNAVAILABLE',
}

export enum ReaderUnavailableReason {
  BLOCKING_FIRMWARE_UPDATE = 'BLOCKING_FIRMWARE_UPDATE',
  BLUETOOTH_DISABLED = 'BLUETOOTH_DISABLED',
  BLUETOOTH_FAILURE = 'BLUETOOTH_FAILURE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  MAX_READERS_CONNECTED = 'MAX_READERS_CONNECTED',
  NONE = 'NONE',
  NOT_CONNECTED_TO_INTERNET = 'NOT_CONNECTED_TO_INTERNET',
  READER_TIMEOUT = 'READER_TIMEOUT',
  REVOKED_BY_DEVICE = 'REVOKED_BY_DEVICE',
  SECURE_CONNECTION_NETWORK_FAILURE = 'SECURE_CONNECTION_NETWORK_FAILURE',
  SECURE_CONNECTION_TO_SQUARE_FAILURE = 'SECURE_CONNECTION_TO_SQUARE_FAILURE',
  TAP_TO_PAY_ERROR = 'TAP_TO_PAY_ERROR',
  TAP_TO_PAY_IS_NOT_LINKED = 'TAP_TO_PAY_IS_NOT_LINKED',
  // Android-specific reasons
  OFFLINE_SESSION_EXPIRED = 'OFFLINE_SESSION_EXPIRED',
  READER_UNAVAILABLE_OFFLINE = 'READER_UNAVAILABLE_OFFLINE',
  OFFLINE_MODE_DISABLED = 'OFFLINE_MODE_DISABLED',
  READER_UPDATE_FAILED = 'READER_UPDATE_FAILED',
  BLOCKING_UPDATE = 'BLOCKING_UPDATE',
  MERCHANT_SUSPENDED = 'MERCHANT_SUSPENDED',
  MERCHANT_INELIGIBLE = 'MERCHANT_INELIGIBLE',
  MERCHANT_NOT_ACTIVATED = 'MERCHANT_NOT_ACTIVATED',
  DEVICE_NOT_SUPPORTED = 'DEVICE_NOT_SUPPORTED',
  READER_FIRMWARE_UPDATE_REQUIRED = 'READER_FIRMWARE_UPDATE_REQUIRED',
  READER_NOT_SUPPORTED = 'READER_NOT_SUPPORTED',
  DEVICE_ROOTED = 'DEVICE_ROOTED',
  DEVICE_DEVELOPER_MODE = 'DEVICE_DEVELOPER_MODE',
  DISABLED = 'DISABLED',
}

export enum CardEntryMethod {
  CHIP = 'CHIP',
  EMV = 'EMV',
  CONTACTLESS = 'CONTACTLESS',
  SWIPED = 'SWIPED',
}

// Offline Mode Enums
export enum OfflinePaymentQueueError {
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  UNEXPECTED = 'UNEXPECTED',
  UNSUPPORTED_SANDBOX_ENVIRONMENT = 'UNSUPPORTED_SANDBOX_ENVIRONMENT',
}

export enum OfflinePaymentStatus {
  QUEUED = 'QUEUED',
  UPLOADED = 'UPLOADED',
  FAILED_TO_UPLOAD = 'FAILED_TO_UPLOAD',
  FAILED_TO_PROCESS = 'FAILED_TO_PROCESS',
  PROCESSED = 'PROCESSED',
  UNKNOWN = 'UNKNOWN',
}

export enum ProcessingMode {
  ONLINE_ONLY = 0,
  OFFLINE_ONLY = 1,
  AUTO_DETECT = 2,
}
